version: 2
updates:
- package-ecosystem: gradle
  directory: /
  schedule:
    # Defaults to first day of the month.
    interval: monthly
  open-pull-requests-limit: 20
  reviewers:
  - cameron-thomson-bsl
  labels:
  - dependencies
  ignore:
    - dependency-name: "net.ltgt.errorprone"
    - dependency-name: "com.google.errorprone:error_prone_core"
    - dependency-name: "org.spockframework:spock-bom"
